m = {}

m.message_types = {
    [1] = "SSH_MSG_DISCONNECT",
    [2] = "SSH_MSG_IGNORE",
    [3] = "SSH_MSG_UNIMPLEMENTED",
    [4] = "SSH_MSG_DEBUG",
    [5] = "SSH_MSG_SERVICE_REQUEST",
    [6] = "SSH_MSG_SERVICE_ACCEPT",
    [7] = "SSH_MSG_EXT_INFO",
    [50] = "SSH_MSG_USERAUTH_REQUEST",
    [51] = "SSH_MSG_USERAUTH_FAILURE",
    [52] = "SSH_MSG_USERAUTH_SUCCESS",
    [53] = "SSH_MSG_USERAUTH_BANNER",
    [60] = "SSH_MSG_USERAUTH_PK_OK",
    [80] = "SSH_MSG_GLOBAL_REQUEST",
    [81] = "SSH_MSG_REQUEST_SUCCESS",
    [82] = "SSH_MSG_REQUEST_FAILURE",
    [90] = "SSH_MSG_CHANNEL_OPEN",
    [91] = "SSH_MSG_CHANNEL_OPEN_CONFIRMATION",
    [92] = "SSH_MSG_CHANNEL_OPEN_FAILURE",
    [93] = "SSH_MSG_CHANNEL_WINDOW_ADJUST",
    [94] = "SSH_MSG_CHANNEL_DATA",
    [95] = "SSH_MSG_CHANNEL_EXTENDED_DATA",
    [96] = "SSH_MSG_CHANNEL_EOF",
    [97] = "SSH_MSG_CHANNEL_CLOSE",
    [98] = "SSH_MSG_CHANNEL_REQUEST",
    [99] = "SSH_MSG_CHANNEL_SUCCESS",
    [100] = "SSH_MSG_CHANNEL_FAILURE"
}

m.reason_codes = {
    [1] = "SSH_DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECT",
    [2] = "SSH_DISCONNECT_PROTOCOL_ERROR",
    [3] = "SSH_DISCONNECT_KEY_EXCHANGE_FAILED",
    [4] = "SSH_DISCONNECT_RESERVED",
    [5] = "SSH_DISCONNECT_MAC_ERROR",
    [6] = "SSH_DISCONNECT_COMPRESSION_ERROR",
    [7] = "SSH_DISCONNECT_SERVICE_NOT_AVAILABLE",
    [8] = "SSH_DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTED",
    [9] = "SSH_DISCONNECT_HOST_KEY_NOT_VERIFIABLE",
    [10] = "SSH_DISCONNECT_CONNECTION_LOST",
    [11] = "SSH_DISCONNECT_BY_APPLICATION",
    [12] = "SSH_DISCONNECT_TOO_MANY_CONNECTIONS",
    [13] = "SSH_DISCONNECT_AUTH_CANCELLED_BY_USER",
    [14] = "SSH_DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLE",
    [15] = "SSH_DISCONNECT_ILLEGAL_USER_NAME",
}

return m;